connect 2/Connect/Controllers/QuestionController.cs
using Connect.Models;
using Connect.Models.Core;
using Connect.Models.Core.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.SignalR;
using Connect.Controllers.Hubs;
using System.Text;
using System.IO;
using System.Web.UI;
using Util;
using System.Net;
using Connect.Services;

namespace Connect.Controllers
{
    [TimeFilter]
    [System.Web.Http.Authorize]
    public class QuestionController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult Post(string text)
        {
            if (!TimeService.IsValidPostingTime())
                return Content(TimeService.READ_ONLY);
            if (text.Length > 2 && User.Identity.IsAuthenticated)
            {
                string currentUserId = User.Identity.GetUserId();
                ApplicationUser user = db.Users.Find(currentUserId);
                Question question = new Question { question = text, dateCreated = DateTime.Now, createdBy = user };
                db.Entry(question).State = System.Data.Entity.EntityState.Added;
                db.Questions.Add(question);
                db.SaveChanges();
                var lastPostedQuestion = PartialView("~/Views/Question/_Question.cshtml", question).RenderToString();

                var context = GlobalHost.ConnectionManager.GetHubContext<QuestionHub>();
                context.Clients.All.questions(lastPostedQuestion);

                context.Clients.All.qcount(Json(AnsweredCount()));

                return new HttpStatusCodeResult(200, "Question Added");
            }
            return new HttpStatusCodeResult(400, "Not valid");
        }

        public ActionResult Reply(int id, string answer, bool important, int rating)
        {
            if (!string.IsNullOrEmpty(answer) && User.Identity.IsAuthenticated)
            {
                ApplicationUser user = db.Users.Find(User.Identity.GetUserId());
                Question question = db.Questions.Find(id);
                question.answer = answer;
                question.answeredBy = user;
                question.Important = important;
                question.Rating = rating;
                question.dateAnswered = DateTime.Now;
                db.Entry(question).State = System.Data.Entity.EntityState.Modified;
                db.Entry(question).Reference(q => q.createdBy).Load();
                db.SaveChanges();
                var context = GlobalHost.ConnectionManager.GetHubContext<QuestionHub>();
                ViewBag.questions = new List<Question>() { question };

                var lastAnsweredQuestion = PartialView("~/Views/Question/_Answers.cshtml").RenderToString();
                context.Clients.All.answers(lastAnsweredQuestion);

                context.Clients.All.qcount(Json(AnsweredCount()));

                return new HttpStatusCodeResult(200, "Replay Added");
            }
            return new HttpStatusCodeResult(400, "Not valid");
        }

        public ActionResult MyQuestions()
        {
            if (ModelState.IsValid && User.Identity.IsAuthenticated)
            {
                string currentUserId = User.Identity.GetUserId();
                var questions = (from q in db.Questions where q.createdBy.Id == currentUserId orderby q.dateCreated descending select q).ToList();
                ViewBag.questions = questions;
                return PartialView("~/Views/Question/_Answers.cshtml");
            }
            return new HttpStatusCodeResult(400, "Not valid");
        }

        public ActionResult Similar(string text)
        {
            var questions = db.Questions.Where(q => q.question.ToLower().StartsWith(text.ToLower())).ToList();
            ViewBag.questions = questions;
            return PartialView("~/Views/Question/_Questions.cshtml");
        }

        public ActionResult Questions(int? previous)
        {
            var questions = (from q in db.Questions
                             where q.answer == null && q.Id > (previous ?? 0)
                             orderby q.Id descending
                             select q).ToList();
            var recentQuestion = questions.FirstOrDefault();
            ViewBag.questions = questions;
            ViewBag.recentQuestionIndex = recentQuestion != null ? recentQuestion.Id : 0;
            return PartialView("~/Views/Question/_Questions.cshtml");
        }

        public ActionResult Answers()
        {
            var questions = (from q in db.Questions
                             where q.answer != null
                             orderby q.dateAnswered descending
                             select q).Take(25).ToList();
            ViewBag.questions = questions;
            return PartialView("~/Views/Question/_Answers.cshtml");
        }

        public ActionResult respondEditor(int id)
        {
            ViewBag.question = db.Questions.Find(id);
            return PartialView("~/Views/Question/_respondEditor.cshtml");
        }

        public ActionResult UnAnsCount()
        {
            return Json(UnAnsweredCount());
        }

        public ActionResult AnsCount()
        {
            return Json(AnsweredCount());
        }
        public ActionResult Broadcast(string msg)
        {
            GlobalHost.ConnectionManager.GetHubContext<QuestionHub>().Clients.All.broadcast(msg);
            return Content("Message broadcasted.");
        }

        private List<int> AnsweredCount()
        {
            int answered = (from q in db.Questions where q.answer != null select q).Count();
            int total = db.Questions.Count();
            return new List<int> { answered, total };
        }
        private List<int> UnAnsweredCount()
        {
            int answered = (from q in db.Questions where q.answer == null select q).Count();
            int total = db.Questions.Count();
            return new List<int> { answered, total };
        }

        public ActionResult Phrases()
        {
            ViewBag.phrases = db.Phrases.OrderByDescending(p => p.Id).ToList();
            return PartialView("~/Views/Question/_phrases.cshtml");
        }
        public ActionResult AddPhrase(string text)
        {
            if (!String.IsNullOrEmpty(text))
            {
                var existingPhrase = db.Phrases.Where(p => p.Text.Equals(text, StringComparison.InvariantCultureIgnoreCase)).FirstOrDefault();
                if (existingPhrase == null)
                {
                    Phrase phrase = new Phrase { Text = text };
                    db.Phrases.Add(phrase);
                    db.Entry(phrase).State = System.Data.Entity.EntityState.Added;
                    db.SaveChanges();
                }
                return Content("Added");
            }
            return new HttpStatusCodeResult(HttpStatusCode.OK);
        }

        public ActionResult Like(int id)
        {
            string currentUserId = User.Identity.GetUserId();
            Question question = db.Questions.Find(id);
            if (!String.IsNullOrEmpty(currentUserId) && question != null && question.createdBy.Id != currentUserId)
            {
                var alreadyLiked = (from l in db.Likes where l.User.Id == currentUserId && l.Question.Id == question.Id select l).FirstOrDefault();
                if (alreadyLiked == null)
                {
                    Like like = new Like() { UserId = currentUserId, Question = question };
                    db.Entry(like).State = System.Data.Entity.EntityState.Added;
                    db.Likes.Add(like);
                    db.SaveChanges();
                }
                var likeCount = (from l in db.Likes where l.Question.Id == question.Id select l).Count();
                return Content(likeCount.ToString());
            }
            return new HttpStatusCodeResult(400, "Not valid");
        }
    }
}

connect 2/Connect/Controllers/ReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Connect.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ReportController : Controller
    {
        // GET: Report
        public ActionResult Index()
        {
            return Redirect("~/Reports/ReportViewer.aspx");
        }
    }
}

connect 2/Connect/Controllers/TimeController.cs
using Connect.Controllers.Hubs;
using Connect.Models;
using Connect.Models.Core;
using Connect.Services;
using Microsoft.AspNet.SignalR;
using Microsoft.Practices.Unity;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Unity.Attributes;

namespace Connect.Controllers
{
    public class TimeController : Controller
    {
        [Dependency("TimeService")]
        public TimeService TimeService { get; set; }
        [Dependency("SettingsService")]
        public SettingsService SettingsService { get; set; }

        ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult Index()
        {
            Models.Core.Session session = TimeService.CurrentSession(); 
            if (session != null && TimeService.IsToday(session))
            {
                var countdownSeconds = session.StartTime.Subtract(DateTime.Now).TotalSeconds;
                if (session.StartTime <= DateTime.Now && DateTime.Now <= session.EndTime)
                {
                    return RedirectToAction("index", "home");
                }
                if (countdownSeconds > 0)
                {
                    ViewBag.currentSession = session;
                    ViewBag.countdownSeconds = countdownSeconds;
                }
                else
                {
                    var msg = SettingsService.GetSettings().SessionCompleteMessage;
                    ViewBag.msg = String.IsNullOrEmpty(msg) ? "Session completed . ." : msg;
                }
            }
            else
            {
                var msg = SettingsService.GetSettings()?.NoSessionsToday;
                ViewBag.msg = String.IsNullOrEmpty(msg) ? "No sessions scheduled for today" : msg;
            }
            return View();
        }
        public ActionResult Duration()
        {
            return Json(TimeService.Duration());
        }

        public ActionResult ExtendSession(int minutes)
        {
            var session = TimeService.CurrentSession();
            if (session != null)
            {
                session.EndTime = session.EndTime.AddMinutes(minutes);
                db.Entry(session).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();

                GlobalHost.ConnectionManager.GetHubContext<QuestionHub>().Clients.All.sessionExtend(@"<script type='text/javascript'>loadSessionTime();</script>");

                return Content("Session Time Updated");
            }
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }

        public ActionResult SessionTime(string from, string to)
        {
            if (!String.IsNullOrEmpty(from) && !String.IsNullOrEmpty(to))
            {
                DateTime fromTime = Convert.ToDateTime(from);
                DateTime toTime = Convert.ToDateTime(to);

                DateTime fromTimeStamp = DateTime.Now.Date + new TimeSpan(fromTime.Hour, fromTime.Minute, 00);
                DateTime toTimeStamp = DateTime.Now.Date + new TimeSpan(toTime.Hour, toTime.Minute, 00);

                Session session = db.Sessions.FirstOrDefault();
                if (session == null)
                {
                    session = new Models.Core.Session() { StartTime = fromTimeStamp, EndTime = toTimeStamp };
                    db.Entry(session).State = System.Data.Entity.EntityState.Added;
                }
                else
                {
                    session.StartTime = fromTimeStamp;
                    session.EndTime = toTimeStamp;
                    db.Entry(session).State = System.Data.Entity.EntityState.Modified;
                }
                db.SaveChanges();
                return Content("Session timings updated");
            }
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

        }
    }
}

connect 2/Connect/Views/Admin/Index.cshtml
@{
    ViewBag.Title = "Reports";
    Connect.Models.Core.Session session = ViewBag.session;
}

@section head{
    <link href="~/Content/timepicker/css/bootstrap-timepicker.min.css" rel="stylesheet" />
    <link href="~/Content/confirm/jquery-confirm.min.css" rel="stylesheet" />
    <style>
        .digital {
            font-family: 'digital-7';
            font-size: 45px;
            text-align: center;
            vertical-align: middle;
        }

        .panel-body {
            min-height: 75px;
        }

        .panel-body-full {
            min-height: 250px;
        }

        #dateTable td {
            padding: 2px;
        }

        .dateTime {
            width: 80px;
        }
    </style>
}

<div class="row">
    <div class="col-md-12">
        <div class="col-md-12">
            <h2>Dashboard 
            <span style="padding-left:10px;"><a href="@Url.Action("Index","Report")" target="_blank" style="font-size:14px"><i class="fa fa-file-pdf-o"></i> Session Report</a></span></h2>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading">Online Users</div>
                <div class="panel-body digital" id="users">

                </div>
            </div>
        </div>@*Report-1*@
        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading">Total Questions</div>
                <div class="panel-body">
                    <div class="digital" style="color:green" id="totalQuestions"></div>
                </div>
            </div>
        </div>@*Report-2*@
        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading">Answered Questions</div>
                <div class="panel-body">
                    <div class="digital" style="color:blue" id="answeredQuestions"></div>
                </div>
            </div>
        </div>@*Report-3*@
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="col-md-3">
            <div class="panel panel-default">
                <div class="panel-heading">
                    High Rated Questions
                </div>
                <div class="panel-body panel-body-full">
                    <table class="table table-striped table-bordered">
                        <thead>
                            <tr>
                                <th>Rating</th>
                                <th>Questions</th>
                                <th>Percentage</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var entry in ViewBag.topRatedQuestions)
                            {
                                <tr>
                                    <td>@entry.user</td>
                                    <td>@entry.count</td>
                                    <td>@((((float)entry.count / (float)ViewBag.totalQuestions) * 100).ToString("N0"))</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>@*Report-1*@
        <div class="col-md-3">
            <div class="panel panel-default">
                <div class="panel-heading">Most Questions Asked By</div>
                <div class="panel-body panel-body-full">
                    <table class="table table-striped table-bordered">
                        <thead>
                            <tr>
                                <th>User</th>
                                <th>Posted</th>
                                <th>Percentage</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var entry in ViewBag.groupByUsersList)
                            {
                                <tr>
                                    <td>@entry.user</td>
                                    <td>@entry.count</td>
                                    <td>@((((float)entry.count / (float)ViewBag.totalQuestions) * 100).ToString("N0"))</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>@*Report-2*@
        <div class="col-md-3">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Most Questions Answered To
                </div>
                <div class="panel-body panel-body-full">
                    <table class="table table-striped table-bordered">
                        <thead>
                            <tr>
                                <th>User</th>
                                <th>Answers</th>
                                <th>Percentage</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var entry in ViewBag.topUsersGotAnswers)
                            {
                                <tr>
                                    <td>@entry.user</td>
                                    <td>@entry.count</td>
                                    <td>@((((float)entry.count / (float)ViewBag.totalQuestions) * 100).ToString("N0"))</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>@*Report-3*@
        <div class="col-md-3">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Good Questions By
                </div>
                <div class="panel-body panel-body-full">
                    <table class="table table-striped table-bordered">
                        <thead>
                            <tr>
                                <th>User</th>
                                <th>Questions</th>
                                <th>Percentage</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var entry in ViewBag.topGoodQuestions)
                            {
                                <tr>
                                    <td>@entry.user</td>
                                    <td>@entry.count</td>
                                    <td>@((((float)entry.count / (float)ViewBag.totalQuestions) * 100).ToString("N0"))</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>@*Report-4*@
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Session Settings
            </div>
            <div class="panel-body" style="height:100px;max-height:100px">
                <h5>Set today's session Time : </h5>
                <table id="dateTable">
                    <tbody>
                        <tr>
                            <td><b>From</b> <input type="text" id="from" class="dateTime" value="@session.StartTime.ToString("hh:mm tt")" /></td>
                            <td><b>To</b> <input type="text" id="to" class="dateTime" value="@session.EndTime.ToString("hh:mm tt")" /></td>
                            <td><input type="button" id="updateSession" value="Update" /></td>
                            <td id="updateStatus"></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>

@section Scripts {
    <script src="~/Content/timepicker/js/bootstrap-timepicker.min.js"></script>
    <script src="~/Scripts/jquery.signalR-2.2.0.min.js"></script>
    <script src="~/signalr/hubs"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('.dateTime').timepicker({ showMeridian: false });
            qcount();
            initSignalR();
        })

        $('#updateSession').click(function () {
            $.ajax({
                url: "@Url.Action("SessionTime", "Time")",
                method: 'post',
                data: { from: $('#from').val(), to: $('#to').val() },
                beforeSend: function () {
                    $('#updateStatus').html('Working,Please Wait . . .');
                },
                success: function (result) {
                    $('#updateStatus').html('');
                }
            });
        })

        function qcount() {
            $.ajax({
                url: "@Url.Action("AnsCount", "Question")",
                method: 'post',
                success: function (result) {
                    showQCount(result[0], result[1]);
                }
            });
        }

        function showQCount(ans, total) {
            $("#answeredQuestions").html(ans);
            $("#totalQuestions").html(total);
        }

        function  () {
            $(function () {
                var chat = $.connection.questionHub;
                chat.client.users = function (msg) {
                    $("#users").html(msg);
                };
                chat.client.qcount = function (msg) {
                    showQCount(msg.Data[0], msg.Data[1]);
                };
                $.connection.hub.start().done(function () {
                });
            });
        }
    </script>
}